### ISSUE TITLE
Uses OMZ

### ISSUE THREAD

**Issue by DanKGooGLy** [Kyza/linux-like-windows-terminal#2]
Windows is already slow enough, why make it slower with ohmyzsh?

**Comment by ghost** [comment]
when the windows is sus!

**Comment by Kyza** [comment]
> Windows is already slow enough, why make it slower with ohmyzsh?

~~Windows is so slow that the slowness of OMZ pales in comparison. Therefore it's acceptable.~~

OMZ is gone.
![woe](https://user-images.githubusercontent.com/40003440/116179922-18946780-a6e6-11eb-8cb2-0ab9205ce84d.gif)
